main:
  push:
    - name: "同步到 GitHub"
      imports: https://cnb.cool/dmxapi/claude-code-my/-/blob/main/env.yml
      runner:
        tags: cnb:arch:amd64
        cpus: 1
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/YeSongYun/dmxapi.doc.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            force: true

  pull_request:
    - name: "AI 代码初审"
      imports: https://cnb.cool/dmxapi/claude-code-my/-/blob/main/env.yml
      runner:
        tags: cnb:arch:amd64
        cpus: 1
      stages:
        - name: code-review
          image: cnbcool/code-review:latest
          settings:
            output: ./code_review.json
            context: 300
            comment: true
            max_comments: 50
            max_files: 300
            max_diff_size: 256000
            fail_on_critical: true

    - name: "AI 代码复审"
      imports: https://cnb.cool/dmxapi/claude-code-my/-/blob/main/env.yml
      runner:
        tags: cnb:arch:amd64
        cpus: 1
      stages:
        - name: 代码评审
          image: cnbcool/ai-review:latest
          settings:
            type: code-review
            ai_chat_url: ${AI_CHAT_URL}
            ai_token: ${AI_TOKEN}
            ai_model: ${AI_MODEL}
            pr_comment: true
            max_comments: 50
