main:
  push:
    - imports: https://cnb.cool/dmxapi/claude-code-my/-/blob/main/env.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          script:
            - git config lfs.allowincompletepush true
            - git remote add target https://${GIT_USERNAME}:${GIT_ACCESS_TOKEN}@github.com/YeSongYun/dmxapi.doc.git || true
            - git push target --all --force
            - git push target --tags --force         